version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  pre-release:
    executor: node-executor
    steps:
      - checkout
      
      - run:
          name: Set Up npm Cache
          command: |
            mkdir -p ~/.npm && echo "Setting up npm cache"
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      
      - run:
          name: Install Dependencies
          command: npm ci
      
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Configure Git
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"

      - run:
          name: Get Next RC Version
          command: |
            set -e
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            ALL_VERSIONS=$(npm view test-package-lema2 versions --json)
            CURRENT_RC=$(echo $ALL_VERSIONS | jq -r '.[]' | grep "^${CURRENT_VERSION}-rc\." || true)
            if [ -z "$CURRENT_RC" ]; then
              NEXT_VERSION="${CURRENT_VERSION}-rc.1"
            else
              HIGHEST_RC=$(echo "$CURRENT_RC" | sort -V | tail -1)
              NEXT_VERSION=$(npx semver "$HIGHEST_RC" --increment prerelease --preid rc)
            fi
            echo "export NEXT_VERSION=$NEXT_VERSION" >> $BASH_ENV
            echo "Next RC version: $NEXT_VERSION"

      - run:
          name: Update Version in package.json
          command: npm version $NEXT_VERSION --no-git-tag-version

      - run:
          name: Debug Environment Variable
          command: |
             echo "Variable is available: $NPM_TOKEN"

      - run:
          name: Set Up npm Authentication
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish Pre-release to npm
          command: npm publish --tag rc
          environment:
            NODE_AUTH_TOKEN: $NPM_TOKEN

      - run:
          name: Create and Push Git Tag
          command: |
            git tag v$NEXT_VERSION
            git push origin v$NEXT_VERSION

      - run:
          name: Generate Release Notes
          command: |
            current_tag=$(git describe --tags)
            previous_tag=$(git describe --tags --abbrev=0 HEAD^)
            commits=$(git log $previous_tag..$current_tag --oneline)
            RELEASE_BODY="$commits"
            echo "$commits" > release_notes.md

      - run:
          name: Debug Environment Variable
          command: |
             echo "Variable is available: $GITHUB_TOKEN"

      - run:
          name: Print All Environment Variables
          command: printenv

      - run:
          name: Create GitHub Release
          shell: /bin/bash
          command: |
            # Debug token substitution
            if [ -z "$GITHUB_TOKEN" ]; then
              echo "❌ GITHUB_TOKEN is not set"
              exit 1
            else
              echo "✅ GITHUB_TOKEN is set: ${GITHUB_TOKEN:0:4}***"
            fi

            # Debug other variables
            echo "NEXT_VERSION: $NEXT_VERSION"
            echo "RELEASE_BODY: $RELEASE_BODY"

            # Generate payload
            PAYLOAD=$(jq -n --arg tag_name "v$NEXT_VERSION" \
                            --arg name "Release v$NEXT_VERSION" \
                            --arg body "$RELEASE_BODY" \
                            '{tag_name: $tag_name, name: $name, body: $body, draft: false, prerelease: true}')
            echo "Generated payload: $PAYLOAD"

            # Create release
            curl -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$PAYLOAD" \
              https://api.github.com/repos/lemadv/test-package/releases

workflows:
  version: 2
  pre-release-workflow:
    jobs:
      - pre-release
