name: Pre-release Workflow

on:
  push:
    branches:
      - staging

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Bump pre-release version
        run: |
          npm version prerelease --preid=rc -m "Pre-release: %s"

      - name: Ensure Git working directory is clean
        run: |
            git add .
            git commit -m "Committing changes before version bump" || echo "No changes to commit"

      - name: Push version bump and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:staging --follow-tags

      - name: Publish pre-release to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag rc
