name: Pre-release Workflow

on:
  push:
    branches:
      - staging

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache npm tarballs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Get current version from npm
        id: get-version
        run: |
          CURRENT_VERSION=$(npm view test-package version)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Calculate next version
        id: calculate-version
        run: |
          # Use a tool like semver to increment the version
          NEXT_VERSION=$(npx semver ${{ env.current_version }} --increment prerelease --preid=rc)
          echo "next_version=$NEXT_VERSION" >> $GITHUB_ENV
          echo "Calculated next_version: $NEXT_VERSION"

      - name: Publish pre-release to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag rc
  
      - name: Create and push Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v${{ env.next_version }}
          git push origin v${{ env.next_version }}
